language: python
sudo: false

cache:
  directories:
    - $HOME/.pip-cache/

matrix:
  include:
    - python: "2.7"
      env: TOXENV=py27 PIP_DOWNLOAD_CACHE=$HOME/.pip-cache
    - python: "3.3"
      env: TOXENV=py33 PIP_DOWNLOAD_CACHE=$HOME/.pip-cache
    - python: "3.4"
      env: TOXENV=py34 PIP_DOWNLOAD_CACHE=$HOME/.pip-cache
    - python: "3.5"
      env: TOXENV=py35 PIP_DOWNLOAD_CACHE=$HOME/.pip-cache
  allow_failures:
    - python: "3.5-dev"
      env: TOXENV=py35 PIP_DOWNLOAD_CACHE=$HOME/.pip-cache
    - python: "nightly"
      env: TOXENV=py36 PIP_DOWNLOAD_CACHE=$HOME/.pip-cache

install:
  - git config --global user.email "travisci@manheim.com"
  - git config --global user.name "travisci"
  - pip install tox
  - pip install codecov
  - pip freeze

script:
  - tox -r

after_success:
  - codecov

notifications:
  email:
    on_success: always
    on_failure: always
branches:
  except:
    - /^noci-.*$/
